# La validation se fait directement sur les entitées

#Dwade75\ApiRestBundle\Entity\Place:
#    constraints:
#        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
#    properties:
#        name:
#            - NotBlank: ~
#            - Type: string
#        address:
#            - NotBlank: ~
#            - Type: string